# Generated by Django 4.2.6 on 2023-10-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_remove_member_memberid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='contactNumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='dateOfBirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='joinDate',
            new_name='join_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='membershipExpiryDate',
            new_name='membership_expiry_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='membershipPlan',
            new_name='membership_plan',
        ),
    ]
