# Generated by Django 4.2.6 on 2023-10-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_membershipplan_alter_member_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
