# Generated by Django 4.2.6 on 2023-10-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_trainer_remove_attendance_attendancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
