# Generated by Django 4.2.6 on 2023-11-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_alter_attendance_member_alter_member_membership_plan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
