# Generated by Django 4.2.6 on 2023-11-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_alter_gymclass_description_alter_gymclass_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='+256', max_length=20),
            preserve_default=False,
        ),
    ]
