# Generated by Django 4.2.6 on 2024-01-31 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0018_gymclass_price_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='membershipPlan',
            new_name='membership_plan',
        ),
    ]
