# Generated by Django 4.2.6 on 2024-01-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0019_rename_membershipplan_subscription_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gym_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.gymclass'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='console.member'),
        ),
    ]
