# Generated by Django 4.2.6 on 2024-01-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0020_payment_gym_class_payment_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
