# Generated by Django 4.2.6 on 2024-01-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0022_alter_subscription_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
