# Generated by Django 4.2.6 on 2024-10-15 04:27

from django.db import migrations, models
import django.utils.timezone

def set_date_to_created_at(apps, schema_editor):
    Payment = apps.get_model('console', 'Payment')
    for payment in Payment.objects.all():
        payment.date = payment.created_at
        payment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('console', '0023_alter_subscription_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(set_date_to_created_at),
    ]
